name: pacmandart
version: 0.3.0
author: Bla <Bla>
description: A Dart implementation of the famous pacman Game.

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"

dependencies:
  http: ">=0.13.0 <1.0.0"

environment:
  sdk: '>=2.10.0 <3.0.0'
